// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: eve_launcher/gateway.proto
#ifndef GRPC_eve_5flauncher_2fgateway_2eproto__INCLUDED
#define GRPC_eve_5flauncher_2fgateway_2eproto__INCLUDED

#include "eve_launcher/gateway.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace eve_launcher {
namespace gateway {

class GatewayService final {
 public:
  static constexpr char const* service_full_name() {
    return "eve_launcher.gateway.GatewayService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::eve_launcher::Event>> PublishEvent(::grpc::ClientContext* context, ::eve_launcher::gateway::DefaultResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::eve_launcher::Event>>(PublishEventRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::eve_launcher::Event>> AsyncPublishEvent(::grpc::ClientContext* context, ::eve_launcher::gateway::DefaultResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::eve_launcher::Event>>(AsyncPublishEventRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::eve_launcher::Event>> PrepareAsyncPublishEvent(::grpc::ClientContext* context, ::eve_launcher::gateway::DefaultResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::eve_launcher::Event>>(PrepareAsyncPublishEventRaw(context, response, cq));
    }
  private:
    virtual ::grpc::ClientWriterInterface< ::eve_launcher::Event>* PublishEventRaw(::grpc::ClientContext* context, ::eve_launcher::gateway::DefaultResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::eve_launcher::Event>* AsyncPublishEventRaw(::grpc::ClientContext* context, ::eve_launcher::gateway::DefaultResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::eve_launcher::Event>* PrepareAsyncPublishEventRaw(::grpc::ClientContext* context, ::eve_launcher::gateway::DefaultResponse* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientWriter< ::eve_launcher::Event>> PublishEvent(::grpc::ClientContext* context, ::eve_launcher::gateway::DefaultResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::eve_launcher::Event>>(PublishEventRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::eve_launcher::Event>> AsyncPublishEvent(::grpc::ClientContext* context, ::eve_launcher::gateway::DefaultResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::eve_launcher::Event>>(AsyncPublishEventRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::eve_launcher::Event>> PrepareAsyncPublishEvent(::grpc::ClientContext* context, ::eve_launcher::gateway::DefaultResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::eve_launcher::Event>>(PrepareAsyncPublishEventRaw(context, response, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientWriter< ::eve_launcher::Event>* PublishEventRaw(::grpc::ClientContext* context, ::eve_launcher::gateway::DefaultResponse* response) override;
    ::grpc::ClientAsyncWriter< ::eve_launcher::Event>* AsyncPublishEventRaw(::grpc::ClientContext* context, ::eve_launcher::gateway::DefaultResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::eve_launcher::Event>* PrepareAsyncPublishEventRaw(::grpc::ClientContext* context, ::eve_launcher::gateway::DefaultResponse* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PublishEvent_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PublishEvent(::grpc::ServerContext* context, ::grpc::ServerReader< ::eve_launcher::Event>* reader, ::eve_launcher::gateway::DefaultResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PublishEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_PublishEvent() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PublishEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PublishEvent(::grpc::ServerContext* context, ::grpc::ServerReader< ::eve_launcher::Event>* reader, ::eve_launcher::gateway::DefaultResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPublishEvent(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::eve_launcher::gateway::DefaultResponse, ::eve_launcher::Event>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PublishEvent<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_PublishEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_PublishEvent() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PublishEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PublishEvent(::grpc::ServerContext* context, ::grpc::ServerReader< ::eve_launcher::Event>* reader, ::eve_launcher::gateway::DefaultResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace gateway
}  // namespace eve_launcher


#endif  // GRPC_eve_5flauncher_2fgateway_2eproto__INCLUDED
