// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eve_launcher/graphics.proto

#ifndef PROTOBUF_INCLUDED_eve_5flauncher_2fgraphics_2eproto
#define PROTOBUF_INCLUDED_eve_5flauncher_2fgraphics_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_eve_5flauncher_2fgraphics_2eproto 

namespace protobuf_eve_5flauncher_2fgraphics_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_eve_5flauncher_2fgraphics_2eproto
namespace eve_launcher {
namespace graphics {
}  // namespace graphics
}  // namespace eve_launcher
namespace eve_launcher {
namespace graphics {

enum DirectXMode {
  UNKNOWN = 0,
  DX9 = 1,
  DX11 = 2,
  DirectXMode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  DirectXMode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool DirectXMode_IsValid(int value);
const DirectXMode DirectXMode_MIN = UNKNOWN;
const DirectXMode DirectXMode_MAX = DX11;
const int DirectXMode_ARRAYSIZE = DirectXMode_MAX + 1;

const ::google::protobuf::EnumDescriptor* DirectXMode_descriptor();
inline const ::std::string& DirectXMode_Name(DirectXMode value) {
  return ::google::protobuf::internal::NameOfEnum(
    DirectXMode_descriptor(), value);
}
inline bool DirectXMode_Parse(
    const ::std::string& name, DirectXMode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DirectXMode>(
    DirectXMode_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace graphics
}  // namespace eve_launcher

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::eve_launcher::graphics::DirectXMode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::eve_launcher::graphics::DirectXMode>() {
  return ::eve_launcher::graphics::DirectXMode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_eve_5flauncher_2fgraphics_2eproto
