// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: eve_launcher/installer.proto
#ifndef GRPC_eve_5flauncher_2finstaller_2eproto__INCLUDED
#define GRPC_eve_5flauncher_2finstaller_2eproto__INCLUDED

#include "eve_launcher/installer.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace eve_launcher {
namespace installer {

}  // namespace installer
}  // namespace eve_launcher


#endif  // GRPC_eve_5flauncher_2finstaller_2eproto__INCLUDED
