// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eve_launcher/installer.proto

#ifndef PROTOBUF_INCLUDED_eve_5flauncher_2finstaller_2eproto
#define PROTOBUF_INCLUDED_eve_5flauncher_2finstaller_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "eve_launcher/launcher.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_eve_5flauncher_2finstaller_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_eve_5flauncher_2finstaller_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[16]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_eve_5flauncher_2finstaller_2eproto();
namespace eve_launcher {
namespace installer {
class ComponentSelectionPageOpened;
class ComponentSelectionPageOpenedDefaultTypeInternal;
extern ComponentSelectionPageOpenedDefaultTypeInternal _ComponentSelectionPageOpened_default_instance_;
class ExecutingPageOpened;
class ExecutingPageOpenedDefaultTypeInternal;
extern ExecutingPageOpenedDefaultTypeInternal _ExecutingPageOpened_default_instance_;
class FinishedPageOpened;
class FinishedPageOpenedDefaultTypeInternal;
extern FinishedPageOpenedDefaultTypeInternal _FinishedPageOpened_default_instance_;
class IntroductionPageOpened;
class IntroductionPageOpenedDefaultTypeInternal;
extern IntroductionPageOpenedDefaultTypeInternal _IntroductionPageOpened_default_instance_;
class LauncherInitializationDone;
class LauncherInitializationDoneDefaultTypeInternal;
extern LauncherInitializationDoneDefaultTypeInternal _LauncherInitializationDone_default_instance_;
class LauncherInitializationStarted;
class LauncherInitializationStartedDefaultTypeInternal;
extern LauncherInitializationStartedDefaultTypeInternal _LauncherInitializationStarted_default_instance_;
class LauncherInstallationFailed;
class LauncherInstallationFailedDefaultTypeInternal;
extern LauncherInstallationFailedDefaultTypeInternal _LauncherInstallationFailed_default_instance_;
class LauncherInstallationStarting;
class LauncherInstallationStartingDefaultTypeInternal;
extern LauncherInstallationStartingDefaultTypeInternal _LauncherInstallationStarting_default_instance_;
class LauncherInstalled;
class LauncherInstalledDefaultTypeInternal;
extern LauncherInstalledDefaultTypeInternal _LauncherInstalled_default_instance_;
class ReadyPageOpened;
class ReadyPageOpenedDefaultTypeInternal;
extern ReadyPageOpenedDefaultTypeInternal _ReadyPageOpened_default_instance_;
class RedistInstallationFailed;
class RedistInstallationFailedDefaultTypeInternal;
extern RedistInstallationFailedDefaultTypeInternal _RedistInstallationFailed_default_instance_;
class RedistInstallationStarting;
class RedistInstallationStartingDefaultTypeInternal;
extern RedistInstallationStartingDefaultTypeInternal _RedistInstallationStarting_default_instance_;
class RedistInstalled;
class RedistInstalledDefaultTypeInternal;
extern RedistInstalledDefaultTypeInternal _RedistInstalled_default_instance_;
class StartMenuPageOpened;
class StartMenuPageOpenedDefaultTypeInternal;
extern StartMenuPageOpenedDefaultTypeInternal _StartMenuPageOpened_default_instance_;
class Started;
class StartedDefaultTypeInternal;
extern StartedDefaultTypeInternal _Started_default_instance_;
class TargetDirectoryPageOpened;
class TargetDirectoryPageOpenedDefaultTypeInternal;
extern TargetDirectoryPageOpenedDefaultTypeInternal _TargetDirectoryPageOpened_default_instance_;
}  // namespace installer
}  // namespace eve_launcher
namespace google {
namespace protobuf {
template<> ::eve_launcher::installer::ComponentSelectionPageOpened* Arena::CreateMaybeMessage<::eve_launcher::installer::ComponentSelectionPageOpened>(Arena*);
template<> ::eve_launcher::installer::ExecutingPageOpened* Arena::CreateMaybeMessage<::eve_launcher::installer::ExecutingPageOpened>(Arena*);
template<> ::eve_launcher::installer::FinishedPageOpened* Arena::CreateMaybeMessage<::eve_launcher::installer::FinishedPageOpened>(Arena*);
template<> ::eve_launcher::installer::IntroductionPageOpened* Arena::CreateMaybeMessage<::eve_launcher::installer::IntroductionPageOpened>(Arena*);
template<> ::eve_launcher::installer::LauncherInitializationDone* Arena::CreateMaybeMessage<::eve_launcher::installer::LauncherInitializationDone>(Arena*);
template<> ::eve_launcher::installer::LauncherInitializationStarted* Arena::CreateMaybeMessage<::eve_launcher::installer::LauncherInitializationStarted>(Arena*);
template<> ::eve_launcher::installer::LauncherInstallationFailed* Arena::CreateMaybeMessage<::eve_launcher::installer::LauncherInstallationFailed>(Arena*);
template<> ::eve_launcher::installer::LauncherInstallationStarting* Arena::CreateMaybeMessage<::eve_launcher::installer::LauncherInstallationStarting>(Arena*);
template<> ::eve_launcher::installer::LauncherInstalled* Arena::CreateMaybeMessage<::eve_launcher::installer::LauncherInstalled>(Arena*);
template<> ::eve_launcher::installer::ReadyPageOpened* Arena::CreateMaybeMessage<::eve_launcher::installer::ReadyPageOpened>(Arena*);
template<> ::eve_launcher::installer::RedistInstallationFailed* Arena::CreateMaybeMessage<::eve_launcher::installer::RedistInstallationFailed>(Arena*);
template<> ::eve_launcher::installer::RedistInstallationStarting* Arena::CreateMaybeMessage<::eve_launcher::installer::RedistInstallationStarting>(Arena*);
template<> ::eve_launcher::installer::RedistInstalled* Arena::CreateMaybeMessage<::eve_launcher::installer::RedistInstalled>(Arena*);
template<> ::eve_launcher::installer::StartMenuPageOpened* Arena::CreateMaybeMessage<::eve_launcher::installer::StartMenuPageOpened>(Arena*);
template<> ::eve_launcher::installer::Started* Arena::CreateMaybeMessage<::eve_launcher::installer::Started>(Arena*);
template<> ::eve_launcher::installer::TargetDirectoryPageOpened* Arena::CreateMaybeMessage<::eve_launcher::installer::TargetDirectoryPageOpened>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace eve_launcher {
namespace installer {

// ===================================================================

class Started final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.Started) */ {
 public:
  Started();
  virtual ~Started();

  Started(const Started& from);

  inline Started& operator=(const Started& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Started(Started&& from) noexcept
    : Started() {
    *this = ::std::move(from);
  }

  inline Started& operator=(Started&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Started& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Started* internal_default_instance() {
    return reinterpret_cast<const Started*>(
               &_Started_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Started* other);
  friend void swap(Started& a, Started& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Started* New() const final {
    return CreateMaybeMessage<Started>(nullptr);
  }

  Started* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Started>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Started& from);
  void MergeFrom(const Started& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Started* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .eve_launcher.Host host = 1;
  bool has_host() const;
  void clear_host();
  static const int kHostFieldNumber = 1;
  const ::eve_launcher::Host& host() const;
  ::eve_launcher::Host* release_host();
  ::eve_launcher::Host* mutable_host();
  void set_allocated_host(::eve_launcher::Host* host);

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.Started)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::eve_launcher::Host* host_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class IntroductionPageOpened final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.IntroductionPageOpened) */ {
 public:
  IntroductionPageOpened();
  virtual ~IntroductionPageOpened();

  IntroductionPageOpened(const IntroductionPageOpened& from);

  inline IntroductionPageOpened& operator=(const IntroductionPageOpened& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  IntroductionPageOpened(IntroductionPageOpened&& from) noexcept
    : IntroductionPageOpened() {
    *this = ::std::move(from);
  }

  inline IntroductionPageOpened& operator=(IntroductionPageOpened&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const IntroductionPageOpened& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IntroductionPageOpened* internal_default_instance() {
    return reinterpret_cast<const IntroductionPageOpened*>(
               &_IntroductionPageOpened_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(IntroductionPageOpened* other);
  friend void swap(IntroductionPageOpened& a, IntroductionPageOpened& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline IntroductionPageOpened* New() const final {
    return CreateMaybeMessage<IntroductionPageOpened>(nullptr);
  }

  IntroductionPageOpened* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<IntroductionPageOpened>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const IntroductionPageOpened& from);
  void MergeFrom(const IntroductionPageOpened& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IntroductionPageOpened* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.IntroductionPageOpened)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class LauncherInitializationStarted final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.LauncherInitializationStarted) */ {
 public:
  LauncherInitializationStarted();
  virtual ~LauncherInitializationStarted();

  LauncherInitializationStarted(const LauncherInitializationStarted& from);

  inline LauncherInitializationStarted& operator=(const LauncherInitializationStarted& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LauncherInitializationStarted(LauncherInitializationStarted&& from) noexcept
    : LauncherInitializationStarted() {
    *this = ::std::move(from);
  }

  inline LauncherInitializationStarted& operator=(LauncherInitializationStarted&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const LauncherInitializationStarted& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LauncherInitializationStarted* internal_default_instance() {
    return reinterpret_cast<const LauncherInitializationStarted*>(
               &_LauncherInitializationStarted_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(LauncherInitializationStarted* other);
  friend void swap(LauncherInitializationStarted& a, LauncherInitializationStarted& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LauncherInitializationStarted* New() const final {
    return CreateMaybeMessage<LauncherInitializationStarted>(nullptr);
  }

  LauncherInitializationStarted* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LauncherInitializationStarted>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LauncherInitializationStarted& from);
  void MergeFrom(const LauncherInitializationStarted& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LauncherInitializationStarted* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.LauncherInitializationStarted)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class LauncherInitializationDone final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.LauncherInitializationDone) */ {
 public:
  LauncherInitializationDone();
  virtual ~LauncherInitializationDone();

  LauncherInitializationDone(const LauncherInitializationDone& from);

  inline LauncherInitializationDone& operator=(const LauncherInitializationDone& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LauncherInitializationDone(LauncherInitializationDone&& from) noexcept
    : LauncherInitializationDone() {
    *this = ::std::move(from);
  }

  inline LauncherInitializationDone& operator=(LauncherInitializationDone&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const LauncherInitializationDone& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LauncherInitializationDone* internal_default_instance() {
    return reinterpret_cast<const LauncherInitializationDone*>(
               &_LauncherInitializationDone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(LauncherInitializationDone* other);
  friend void swap(LauncherInitializationDone& a, LauncherInitializationDone& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LauncherInitializationDone* New() const final {
    return CreateMaybeMessage<LauncherInitializationDone>(nullptr);
  }

  LauncherInitializationDone* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LauncherInitializationDone>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LauncherInitializationDone& from);
  void MergeFrom(const LauncherInitializationDone& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LauncherInitializationDone* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.LauncherInitializationDone)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class TargetDirectoryPageOpened final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.TargetDirectoryPageOpened) */ {
 public:
  TargetDirectoryPageOpened();
  virtual ~TargetDirectoryPageOpened();

  TargetDirectoryPageOpened(const TargetDirectoryPageOpened& from);

  inline TargetDirectoryPageOpened& operator=(const TargetDirectoryPageOpened& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TargetDirectoryPageOpened(TargetDirectoryPageOpened&& from) noexcept
    : TargetDirectoryPageOpened() {
    *this = ::std::move(from);
  }

  inline TargetDirectoryPageOpened& operator=(TargetDirectoryPageOpened&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const TargetDirectoryPageOpened& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TargetDirectoryPageOpened* internal_default_instance() {
    return reinterpret_cast<const TargetDirectoryPageOpened*>(
               &_TargetDirectoryPageOpened_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(TargetDirectoryPageOpened* other);
  friend void swap(TargetDirectoryPageOpened& a, TargetDirectoryPageOpened& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TargetDirectoryPageOpened* New() const final {
    return CreateMaybeMessage<TargetDirectoryPageOpened>(nullptr);
  }

  TargetDirectoryPageOpened* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TargetDirectoryPageOpened>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TargetDirectoryPageOpened& from);
  void MergeFrom(const TargetDirectoryPageOpened& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TargetDirectoryPageOpened* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.TargetDirectoryPageOpened)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class ComponentSelectionPageOpened final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.ComponentSelectionPageOpened) */ {
 public:
  ComponentSelectionPageOpened();
  virtual ~ComponentSelectionPageOpened();

  ComponentSelectionPageOpened(const ComponentSelectionPageOpened& from);

  inline ComponentSelectionPageOpened& operator=(const ComponentSelectionPageOpened& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ComponentSelectionPageOpened(ComponentSelectionPageOpened&& from) noexcept
    : ComponentSelectionPageOpened() {
    *this = ::std::move(from);
  }

  inline ComponentSelectionPageOpened& operator=(ComponentSelectionPageOpened&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ComponentSelectionPageOpened& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ComponentSelectionPageOpened* internal_default_instance() {
    return reinterpret_cast<const ComponentSelectionPageOpened*>(
               &_ComponentSelectionPageOpened_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(ComponentSelectionPageOpened* other);
  friend void swap(ComponentSelectionPageOpened& a, ComponentSelectionPageOpened& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ComponentSelectionPageOpened* New() const final {
    return CreateMaybeMessage<ComponentSelectionPageOpened>(nullptr);
  }

  ComponentSelectionPageOpened* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ComponentSelectionPageOpened>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ComponentSelectionPageOpened& from);
  void MergeFrom(const ComponentSelectionPageOpened& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ComponentSelectionPageOpened* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.ComponentSelectionPageOpened)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class StartMenuPageOpened final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.StartMenuPageOpened) */ {
 public:
  StartMenuPageOpened();
  virtual ~StartMenuPageOpened();

  StartMenuPageOpened(const StartMenuPageOpened& from);

  inline StartMenuPageOpened& operator=(const StartMenuPageOpened& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StartMenuPageOpened(StartMenuPageOpened&& from) noexcept
    : StartMenuPageOpened() {
    *this = ::std::move(from);
  }

  inline StartMenuPageOpened& operator=(StartMenuPageOpened&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const StartMenuPageOpened& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StartMenuPageOpened* internal_default_instance() {
    return reinterpret_cast<const StartMenuPageOpened*>(
               &_StartMenuPageOpened_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(StartMenuPageOpened* other);
  friend void swap(StartMenuPageOpened& a, StartMenuPageOpened& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StartMenuPageOpened* New() const final {
    return CreateMaybeMessage<StartMenuPageOpened>(nullptr);
  }

  StartMenuPageOpened* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StartMenuPageOpened>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StartMenuPageOpened& from);
  void MergeFrom(const StartMenuPageOpened& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StartMenuPageOpened* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.StartMenuPageOpened)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class ReadyPageOpened final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.ReadyPageOpened) */ {
 public:
  ReadyPageOpened();
  virtual ~ReadyPageOpened();

  ReadyPageOpened(const ReadyPageOpened& from);

  inline ReadyPageOpened& operator=(const ReadyPageOpened& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReadyPageOpened(ReadyPageOpened&& from) noexcept
    : ReadyPageOpened() {
    *this = ::std::move(from);
  }

  inline ReadyPageOpened& operator=(ReadyPageOpened&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ReadyPageOpened& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReadyPageOpened* internal_default_instance() {
    return reinterpret_cast<const ReadyPageOpened*>(
               &_ReadyPageOpened_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(ReadyPageOpened* other);
  friend void swap(ReadyPageOpened& a, ReadyPageOpened& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReadyPageOpened* New() const final {
    return CreateMaybeMessage<ReadyPageOpened>(nullptr);
  }

  ReadyPageOpened* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReadyPageOpened>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReadyPageOpened& from);
  void MergeFrom(const ReadyPageOpened& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReadyPageOpened* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.ReadyPageOpened)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class ExecutingPageOpened final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.ExecutingPageOpened) */ {
 public:
  ExecutingPageOpened();
  virtual ~ExecutingPageOpened();

  ExecutingPageOpened(const ExecutingPageOpened& from);

  inline ExecutingPageOpened& operator=(const ExecutingPageOpened& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ExecutingPageOpened(ExecutingPageOpened&& from) noexcept
    : ExecutingPageOpened() {
    *this = ::std::move(from);
  }

  inline ExecutingPageOpened& operator=(ExecutingPageOpened&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ExecutingPageOpened& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ExecutingPageOpened* internal_default_instance() {
    return reinterpret_cast<const ExecutingPageOpened*>(
               &_ExecutingPageOpened_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(ExecutingPageOpened* other);
  friend void swap(ExecutingPageOpened& a, ExecutingPageOpened& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ExecutingPageOpened* New() const final {
    return CreateMaybeMessage<ExecutingPageOpened>(nullptr);
  }

  ExecutingPageOpened* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ExecutingPageOpened>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ExecutingPageOpened& from);
  void MergeFrom(const ExecutingPageOpened& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExecutingPageOpened* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.ExecutingPageOpened)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class LauncherInstallationStarting final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.LauncherInstallationStarting) */ {
 public:
  LauncherInstallationStarting();
  virtual ~LauncherInstallationStarting();

  LauncherInstallationStarting(const LauncherInstallationStarting& from);

  inline LauncherInstallationStarting& operator=(const LauncherInstallationStarting& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LauncherInstallationStarting(LauncherInstallationStarting&& from) noexcept
    : LauncherInstallationStarting() {
    *this = ::std::move(from);
  }

  inline LauncherInstallationStarting& operator=(LauncherInstallationStarting&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const LauncherInstallationStarting& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LauncherInstallationStarting* internal_default_instance() {
    return reinterpret_cast<const LauncherInstallationStarting*>(
               &_LauncherInstallationStarting_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(LauncherInstallationStarting* other);
  friend void swap(LauncherInstallationStarting& a, LauncherInstallationStarting& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LauncherInstallationStarting* New() const final {
    return CreateMaybeMessage<LauncherInstallationStarting>(nullptr);
  }

  LauncherInstallationStarting* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LauncherInstallationStarting>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LauncherInstallationStarting& from);
  void MergeFrom(const LauncherInstallationStarting& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LauncherInstallationStarting* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.LauncherInstallationStarting)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class LauncherInstalled final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.LauncherInstalled) */ {
 public:
  LauncherInstalled();
  virtual ~LauncherInstalled();

  LauncherInstalled(const LauncherInstalled& from);

  inline LauncherInstalled& operator=(const LauncherInstalled& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LauncherInstalled(LauncherInstalled&& from) noexcept
    : LauncherInstalled() {
    *this = ::std::move(from);
  }

  inline LauncherInstalled& operator=(LauncherInstalled&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const LauncherInstalled& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LauncherInstalled* internal_default_instance() {
    return reinterpret_cast<const LauncherInstalled*>(
               &_LauncherInstalled_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  void Swap(LauncherInstalled* other);
  friend void swap(LauncherInstalled& a, LauncherInstalled& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LauncherInstalled* New() const final {
    return CreateMaybeMessage<LauncherInstalled>(nullptr);
  }

  LauncherInstalled* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LauncherInstalled>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LauncherInstalled& from);
  void MergeFrom(const LauncherInstalled& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LauncherInstalled* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.LauncherInstalled)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class LauncherInstallationFailed final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.LauncherInstallationFailed) */ {
 public:
  LauncherInstallationFailed();
  virtual ~LauncherInstallationFailed();

  LauncherInstallationFailed(const LauncherInstallationFailed& from);

  inline LauncherInstallationFailed& operator=(const LauncherInstallationFailed& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LauncherInstallationFailed(LauncherInstallationFailed&& from) noexcept
    : LauncherInstallationFailed() {
    *this = ::std::move(from);
  }

  inline LauncherInstallationFailed& operator=(LauncherInstallationFailed&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const LauncherInstallationFailed& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LauncherInstallationFailed* internal_default_instance() {
    return reinterpret_cast<const LauncherInstallationFailed*>(
               &_LauncherInstallationFailed_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    11;

  void Swap(LauncherInstallationFailed* other);
  friend void swap(LauncherInstallationFailed& a, LauncherInstallationFailed& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LauncherInstallationFailed* New() const final {
    return CreateMaybeMessage<LauncherInstallationFailed>(nullptr);
  }

  LauncherInstallationFailed* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LauncherInstallationFailed>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LauncherInstallationFailed& from);
  void MergeFrom(const LauncherInstallationFailed& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LauncherInstallationFailed* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.LauncherInstallationFailed)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class RedistInstallationStarting final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.RedistInstallationStarting) */ {
 public:
  RedistInstallationStarting();
  virtual ~RedistInstallationStarting();

  RedistInstallationStarting(const RedistInstallationStarting& from);

  inline RedistInstallationStarting& operator=(const RedistInstallationStarting& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RedistInstallationStarting(RedistInstallationStarting&& from) noexcept
    : RedistInstallationStarting() {
    *this = ::std::move(from);
  }

  inline RedistInstallationStarting& operator=(RedistInstallationStarting&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const RedistInstallationStarting& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RedistInstallationStarting* internal_default_instance() {
    return reinterpret_cast<const RedistInstallationStarting*>(
               &_RedistInstallationStarting_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    12;

  void Swap(RedistInstallationStarting* other);
  friend void swap(RedistInstallationStarting& a, RedistInstallationStarting& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RedistInstallationStarting* New() const final {
    return CreateMaybeMessage<RedistInstallationStarting>(nullptr);
  }

  RedistInstallationStarting* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RedistInstallationStarting>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RedistInstallationStarting& from);
  void MergeFrom(const RedistInstallationStarting& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RedistInstallationStarting* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.RedistInstallationStarting)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class RedistInstalled final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.RedistInstalled) */ {
 public:
  RedistInstalled();
  virtual ~RedistInstalled();

  RedistInstalled(const RedistInstalled& from);

  inline RedistInstalled& operator=(const RedistInstalled& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RedistInstalled(RedistInstalled&& from) noexcept
    : RedistInstalled() {
    *this = ::std::move(from);
  }

  inline RedistInstalled& operator=(RedistInstalled&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const RedistInstalled& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RedistInstalled* internal_default_instance() {
    return reinterpret_cast<const RedistInstalled*>(
               &_RedistInstalled_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    13;

  void Swap(RedistInstalled* other);
  friend void swap(RedistInstalled& a, RedistInstalled& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RedistInstalled* New() const final {
    return CreateMaybeMessage<RedistInstalled>(nullptr);
  }

  RedistInstalled* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RedistInstalled>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RedistInstalled& from);
  void MergeFrom(const RedistInstalled& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RedistInstalled* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.RedistInstalled)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class RedistInstallationFailed final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.RedistInstallationFailed) */ {
 public:
  RedistInstallationFailed();
  virtual ~RedistInstallationFailed();

  RedistInstallationFailed(const RedistInstallationFailed& from);

  inline RedistInstallationFailed& operator=(const RedistInstallationFailed& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RedistInstallationFailed(RedistInstallationFailed&& from) noexcept
    : RedistInstallationFailed() {
    *this = ::std::move(from);
  }

  inline RedistInstallationFailed& operator=(RedistInstallationFailed&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const RedistInstallationFailed& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RedistInstallationFailed* internal_default_instance() {
    return reinterpret_cast<const RedistInstallationFailed*>(
               &_RedistInstallationFailed_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    14;

  void Swap(RedistInstallationFailed* other);
  friend void swap(RedistInstallationFailed& a, RedistInstallationFailed& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RedistInstallationFailed* New() const final {
    return CreateMaybeMessage<RedistInstallationFailed>(nullptr);
  }

  RedistInstallationFailed* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RedistInstallationFailed>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RedistInstallationFailed& from);
  void MergeFrom(const RedistInstallationFailed& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RedistInstallationFailed* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.RedistInstallationFailed)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// -------------------------------------------------------------------

class FinishedPageOpened final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eve_launcher.installer.FinishedPageOpened) */ {
 public:
  FinishedPageOpened();
  virtual ~FinishedPageOpened();

  FinishedPageOpened(const FinishedPageOpened& from);

  inline FinishedPageOpened& operator=(const FinishedPageOpened& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FinishedPageOpened(FinishedPageOpened&& from) noexcept
    : FinishedPageOpened() {
    *this = ::std::move(from);
  }

  inline FinishedPageOpened& operator=(FinishedPageOpened&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const FinishedPageOpened& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FinishedPageOpened* internal_default_instance() {
    return reinterpret_cast<const FinishedPageOpened*>(
               &_FinishedPageOpened_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    15;

  void Swap(FinishedPageOpened* other);
  friend void swap(FinishedPageOpened& a, FinishedPageOpened& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FinishedPageOpened* New() const final {
    return CreateMaybeMessage<FinishedPageOpened>(nullptr);
  }

  FinishedPageOpened* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FinishedPageOpened>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FinishedPageOpened& from);
  void MergeFrom(const FinishedPageOpened& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FinishedPageOpened* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:eve_launcher.installer.FinishedPageOpened)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_eve_5flauncher_2finstaller_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Started

// .eve_launcher.Host host = 1;
inline bool Started::has_host() const {
  return this != internal_default_instance() && host_ != nullptr;
}
inline const ::eve_launcher::Host& Started::host() const {
  const ::eve_launcher::Host* p = host_;
  // @@protoc_insertion_point(field_get:eve_launcher.installer.Started.host)
  return p != nullptr ? *p : *reinterpret_cast<const ::eve_launcher::Host*>(
      &::eve_launcher::_Host_default_instance_);
}
inline ::eve_launcher::Host* Started::release_host() {
  // @@protoc_insertion_point(field_release:eve_launcher.installer.Started.host)
  
  ::eve_launcher::Host* temp = host_;
  host_ = nullptr;
  return temp;
}
inline ::eve_launcher::Host* Started::mutable_host() {
  
  if (host_ == nullptr) {
    auto* p = CreateMaybeMessage<::eve_launcher::Host>(GetArenaNoVirtual());
    host_ = p;
  }
  // @@protoc_insertion_point(field_mutable:eve_launcher.installer.Started.host)
  return host_;
}
inline void Started::set_allocated_host(::eve_launcher::Host* host) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(host_);
  }
  if (host) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      host = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, host, submessage_arena);
    }
    
  } else {
    
  }
  host_ = host;
  // @@protoc_insertion_point(field_set_allocated:eve_launcher.installer.Started.host)
}

// -------------------------------------------------------------------

// IntroductionPageOpened

// -------------------------------------------------------------------

// LauncherInitializationStarted

// -------------------------------------------------------------------

// LauncherInitializationDone

// -------------------------------------------------------------------

// TargetDirectoryPageOpened

// -------------------------------------------------------------------

// ComponentSelectionPageOpened

// -------------------------------------------------------------------

// StartMenuPageOpened

// -------------------------------------------------------------------

// ReadyPageOpened

// -------------------------------------------------------------------

// ExecutingPageOpened

// -------------------------------------------------------------------

// LauncherInstallationStarting

// -------------------------------------------------------------------

// LauncherInstalled

// -------------------------------------------------------------------

// LauncherInstallationFailed

// -------------------------------------------------------------------

// RedistInstallationStarting

// -------------------------------------------------------------------

// RedistInstalled

// -------------------------------------------------------------------

// RedistInstallationFailed

// -------------------------------------------------------------------

// FinishedPageOpened

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace installer
}  // namespace eve_launcher

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_eve_5flauncher_2finstaller_2eproto
